#!/usr/bin/env python3
"""anim_gif2c.py — GIF 动图 → ESP32 C 数组（4bpp 索引色，不透明+烘底色）

S3-A 交付物：哭泣猫跳舞素材管线
用法:
    python tools/anim_gif2c.py <gif>:<NAME> [<gif>:<NAME> ...] \
        [--outdir main/cat] [--previewdir <dir>] [--scale 1.0]

输出:
    <outdir>/cat_assets.h   — 动画结构体声明（extern）
    <outdir>/cat_assets.c   — 调色板 + 逐帧数据（多输入合并写出）
    <previewdir>/<name>_check.png    — 洋红边框网格（调色板/细节验收）
    <previewdir>/<name>_preview.gif  — 半尺寸动图预览

设计定论（S3-A）:
    - 不做逐像素透明掩码：白底白猫贴纸描边细、有缺口，洪泛必漏（已踩坑）
    - 每个动画 bake 一个底色 bg_color（取四角中位色，GIF 有 alpha 则先合成到该底色）
    - 设备端渲染: 整屏填 bg_color → 居中 blit 不透明帧；同色平移/旋转边缘隐形
    - index 0..15 调色板 RGB565；帧数据 4bpp 打包（高半字节在前）
"""

import argparse
import sys
from pathlib import Path

from PIL import Image, ImageSequence

MAX_COLORS = 16
HEADER_NAME = "cat_assets"


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def load_frames(path: Path):
    im = Image.open(path)
    frames, durs = [], []
    for fr in ImageSequence.Iterator(im):
        durs.append(max(20, int(fr.info.get("duration", 50))))
        frames.append(fr.convert("RGBA"))
    return frames, durs


def bg_color_of(frames) -> tuple:
    """底色 = 首帧四角 RGB 每通道中位。"""
    w, h = frames[0].size
    px = frames[0].load()
    corners = [px[x, y][:3] for x, y in ((0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1))]
    return tuple(sorted(c[i] for c in corners)[1] for i in range(3))


def pack4bpp(idx: bytes) -> bytes:
    out = bytearray((len(idx) + 1) // 2)
    for i, v in enumerate(idx):
        if i & 1:
            out[i >> 1] |= v
        else:
            out[i >> 1] |= v << 4
    return bytes(out)


def convert(path: Path, name: str, scale: float) -> dict:
    frames, durs = load_frames(path)
    if scale != 1.0:
        frames = [f.resize((int(f.width * scale), int(f.height * scale)), Image.LANCZOS)
                  for f in frames]
    w, h = frames[0].size
    bg = bg_color_of(frames)

    # 烘底色: 全部帧合成到 bg 上（有 alpha 的贴纸/无 alpha 的白底图统一处理）
    opaque = []
    for f in frames:
        base = Image.new("RGB", (w, h), bg)
        base.paste(f.convert("RGB"), (0, 0), f.split()[3])
        opaque.append(base)

    # 全局调色板: 拼接所有帧 → MEDIANCUT 量化
    strip = Image.new("RGB", (w, h * len(opaque)))
    for k, f in enumerate(opaque):
        strip.paste(f, (0, k * h))
    pal_img = strip.quantize(colors=MAX_COLORS, method=Image.MEDIANCUT, dither=Image.Dither.NONE)
    pal = pal_img.getpalette() or []
    n_pal = min(MAX_COLORS, len(pal) // 3)
    palette565 = [0] * MAX_COLORS
    for i in range(n_pal):
        palette565[i] = rgb565(pal[i * 3], pal[i * 3 + 1], pal[i * 3 + 2])

    # 逐帧映射 + 打包
    idx_data = []
    for f in opaque:
        q = f.quantize(palette=pal_img, dither=Image.Dither.NONE)
        idx_data.append(pack4bpp(q.tobytes()))
    return dict(name=name, w=w, h=h, n_frames=len(durs), durs=durs,
                bg565=rgb565(*bg), bg=bg, palette=palette565, idx=idx_data)


def emit_c(anims, outdir: Path):
    h_path = outdir / f"{HEADER_NAME}.h"
    c_path = outdir / f"{HEADER_NAME}.c"
    h = ["#pragma once", "// Generated by tools/anim_gif2c.py — DO NOT EDIT",
         "#include <stdint.h>", "",
         "typedef struct {",
         "    const char *name;",
         "    uint16_t w, h, n_frames;",
         "    uint16_t bg_color;            /* RGB565, 整屏底色 */",
         "    const uint16_t *palette;      /* RGB565[16] */",
         "    const uint8_t *const *idx;    /* 4bpp, hi-nibble first */",
         "    const uint16_t *delay_ms;",
         "} cat_anim_t;", ""]
    for a in anims:
        h.append(f"extern const cat_anim_t {a['name']};")
    h_path.write_text("\n".join(h) + "\n", encoding="utf-8")

    kb = lambda lst: sum(len(x) for x in lst) // 1024
    c = ["// Generated by tools/anim_gif2c.py — DO NOT EDIT",
         f'// 帧数据合计: {sum(kb(a["idx"]) for a in anims)}KB',
         f'#include "{HEADER_NAME}.h"', '#include <stdint.h>', ""]
    for a in anims:
        n = a["name"].lower()
        c.append(f"static const uint16_t {n}_pal[{MAX_COLORS}] = {{")
        c.append("    " + ", ".join(f"0x{v:04X}" for v in a["palette"]))
        c.append("};")
        for k, ib in enumerate(a["idx"]):
            c.append(f"static const uint8_t {n}_idx{k}[] = {{{', '.join(f'0x{b:02X}' for b in ib)}}};")
        c.append(f"static const uint8_t *const {n}_idx_t[{a['n_frames']}] = "
                 f"{{{', '.join(f'{n}_idx{k}' for k in range(a['n_frames']))}}};")
        c.append(f"static const uint16_t {n}_dur[{a['n_frames']}] = "
                 f"{{{', '.join(map(str, a['durs']))}}};")
        c.append(f"const cat_anim_t {a['name']} = {{")
        c.append(f'    .name = "{a["name"]}", .w = {a["w"]}, .h = {a["h"]}, '
                 f'.n_frames = {a["n_frames"]}, .bg_color = 0x{a["bg565"]:04X},')
        c.append(f"    .palette = {n}_pal, .idx = {n}_idx_t, .delay_ms = {n}_dur,")
        c.append("};")
        c.append("")
    c_path.write_text("\n".join(c), encoding="utf-8")


def emit_preview(anim: dict, previewdir: Path):
    """从打包数据反解码渲染（与设备端同路径），验调色板/量化/时序。"""
    w, h, n = anim["w"], anim["h"], anim["w"] * anim["h"]
    pal_rgb = [((v >> 8) & 0xF8, (v >> 3) & 0xFC, (v << 3) & 0xF8) for v in anim["palette"]]
    frames = []
    for k in range(anim["n_frames"]):
        img = Image.new("RGB", (w, h))
        px = img.load()
        ib = anim["idx"][k]
        for i in range(n):
            v = ib[i >> 1]
            px[i % w, i // w] = pal_rgb[(v >> 4) if not (i & 1) else (v & 0xF)]
        frames.append(img)
    cols, cell = 6, 160
    rows = (len(frames) + cols - 1) // cols
    sheet = Image.new("RGB", (cell * cols + 8, cell * rows + 8), (255, 0, 255))
    for k, f in enumerate(frames):
        t = f.copy(); t.thumbnail((cell - 8, cell - 8))
        sheet.paste(t, ((k % cols) * cell + 4, (k // cols) * cell + 4))
    sheet.save(previewdir / f"{anim['name']}_check.png")
    small = [f.resize((w // 2, h // 2)) for f in frames]
    small[0].save(previewdir / f"{anim['name']}_preview.gif", save_all=True,
                  append_images=small[1:], duration=anim["durs"], loop=0)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("inputs", nargs="+",
                    help="<gif路径>:<动画名> 可多个，例: a.gif:CAT_FOO b.gif:CAT_BAR")
    ap.add_argument("--outdir", default="main/cat")
    ap.add_argument("--previewdir")
    ap.add_argument("--scale", type=float, default=1.0)
    args = ap.parse_args()

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    previewdir = Path(args.previewdir) if args.previewdir else outdir / "preview"
    previewdir.mkdir(parents=True, exist_ok=True)

    anims = []
    for spec in args.inputs:
        src_s, _, name = spec.rpartition(":")
        if not src_s or not name:
            sys.exit(f"参数格式错误: {spec}（应为 <gif>:<NAME>）")
        anims.append(convert(Path(src_s), name, args.scale))
    emit_c(anims, outdir)
    for a in anims:
        emit_preview(a, previewdir)
        total = sum(len(x) for x in a["idx"])
        print(f"[{a['name']}] {a['w']}x{a['h']} {a['n_frames']}帧 "
              f"bg=RGB{a['bg']} 数据={total / 1024:.0f}KB")


if __name__ == "__main__":
    main()
