#pragma once
// Generated by tools/anim_gif2c.py — DO NOT EDIT
#include <stdint.h>

typedef struct {
    const char *name;
    uint16_t w, h, n_frames;
    uint16_t bg_color;            /* RGB565, 整屏底色 */
    const uint16_t *palette;      /* RGB565[16] */
    const uint8_t *const *idx;    /* 4bpp, hi-nibble first */
    const uint16_t *delay_ms;
} cat_anim_t;

extern const cat_anim_t CAT_A01_PEACHGOMA_CRY;
extern const cat_anim_t CAT_A02_PEACH_FLOORCRY;
extern const cat_anim_t CAT_A03_PEACH_LOOK;
extern const cat_anim_t CAT_A04_PEACH_BOWL;
